name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    env:
      PLATFORM: x64
      CONFIGURATION: Release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore test/AudioDeviceSwitcher.Tests.csproj -p:Platform=x64

      - name: Test
        run: dotnet test test/AudioDeviceSwitcher.Tests.csproj --no-restore --configuration Release -p:Platform=x64 --logger "console;verbosity=detailed"
